[package]

name = "document"
version = "0.0.1"
authors = ["Jake Goulding <jake.goulding@gmail.com>"]

[features]

compile_failure = []

[dependencies.xxhash]

git = "https://github.com/shepmaster/rust-xxhash"
rev = "ff16980e763cba5cb1b75b05604bc503ba3a41f1"
