[package]

name = "document"
version = "0.0.1"
authors = ["Jake Goulding <jake.goulding@gmail.com>"]

[features]

compile_failure = []

[dependencies]

peresil = "0.1.0"

[dependencies.xxhash]

git = "https://github.com/shepmaster/rust-xxhash"
branch = "update-fallout-3"
