[package]

name = "document"
version = "0.0.1"
authors = ["Jake Goulding <jake.goulding@gmail.com>"]

[features]

compile_failure = []

[dependencies.xxhash]

git = "https://github.com/jurily/rust-xxhash"
