[package]

name = "sxd-document"
version = "0.0.1"
authors = ["Jake Goulding <jake.goulding@gmail.com>"]

[features]

compile_failure = []
unstable = []

[dependencies]

peresil = "0.2.0"
typed-arena = "1.0"
